### ISSUE TITLE
Incompatibility with Doctrine's ArrayCollection

### ISSUE THREAD

**Issue by saterond** [skrz/meta#7]
When using Doctrine entities there's a problem with transforming them to arrays.
Example:

``` php
/** @Doctrine\ORM\Mapping\Entity */
class Cart
{
    /** @var CartItem[] */
    public $cartItems;

    public function __construct()
    {
        $this->cartItems = new ArrayCollection();
    }
}
```

[ArrayCollection](http://www.doctrine-project.org/api/common/2.1/class-Doctrine.Common.Collections.ArrayCollection.html) serves as a helper when modifiying the array.
Problems occurs with this:

``` php
/** @var Cart $cart */
$arr = CartMeta::toArray($cart);
```

Because skrz/meta (PhpModule) [applies](%28https://github.com/skrz/meta/blob/master/src/Skrz/Meta/PHP/PhpModule.php#L425%29) casting to child array entities like this:

``` php
foreach ((array)$input['cartItems'] as $k0 => $v0) {
...
}
```

Quickfix is easy - remove the casting. Better solution would be to support ArrayCollections :)

**Comment by jakubkulhan** [comment]
@saterond Can you confirm the fix works with Doctrine's `ArrayCollection`?

**Comment by saterond** [comment]
Tested, worked, done :)
